import { Ingredient, PriceItem, Recipe } from "./types";
import { buildDessertSteps } from "./procedures";

const nutrition = (
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
) => ({
  calories,
  protein,
  carbs,
  fat,
});

const storesFor = (base: number) => ({
  Lidl: +(base * 0.92).toFixed(2),
  Eurospin: +(base * 0.88).toFixed(2),
  Esselunga: +(base * 1.08).toFixed(2),
  Coop: +(base * 1.1).toFixed(2),
  Conad: +(base * 1.04).toFixed(2),
  Despar: +(base * 1.06).toFixed(2),
  Penny: +(base * 0.9).toFixed(2),
  MD: +(base * 0.89).toFixed(2),
  Altro: base,
});

const price = (
  id: string,
  name: string,
  unit: "g" | "ml" | "pz",
  base: number,
  per: number,
  category: PriceItem["category"],
  allergens: string[],
  values = nutrition(0, 0, 0, 0),
): PriceItem => ({
  id,
  name,
  unit,
  price: base,
  per,
  packageQuantity: per,
  category,
  allergens,
  nutrition: values,
  stores: storesFor(base),
});

export const dessertPrices: PriceItem[] = [
  price(
    "zucchero",
    "Zucchero",
    "g",
    1.29,
    1000,
    "Dispensa",
    [],
    nutrition(400, 0, 100, 0),
  ),
  price(
    "burro",
    "Burro",
    "g",
    2.49,
    250,
    "Latticini",
    ["latte"],
    nutrition(717, 1, 1, 81),
  ),
  price(
    "latte",
    "Latte",
    "ml",
    1.39,
    1000,
    "Latticini",
    ["latte"],
    nutrition(46, 3, 5, 2),
  ),
  price(
    "cioccolato-fondente",
    "Cioccolato fondente",
    "g",
    1.79,
    100,
    "Dispensa",
    [],
    nutrition(546, 5, 61, 31),
  ),
  price(
    "cioccolato-latte",
    "Cioccolato al latte",
    "g",
    1.69,
    100,
    "Dispensa",
    ["latte"],
    nutrition(535, 8, 59, 30),
  ),
  price(
    "cacao",
    "Cacao amaro",
    "g",
    2.19,
    250,
    "Dispensa",
    [],
    nutrition(228, 20, 58, 14),
  ),
  price(
    "lievito-dolci",
    "Lievito per dolci",
    "g",
    1.09,
    48,
    "Dispensa",
    [],
    nutrition(100, 0, 25, 0),
  ),
  price(
    "vaniglia",
    "Vaniglia",
    "g",
    1.29,
    4,
    "Dispensa",
    [],
    nutrition(288, 0, 13, 0),
  ),
  price(
    "miele",
    "Miele",
    "g",
    3.49,
    500,
    "Dispensa",
    [],
    nutrition(304, 0, 82, 0),
  ),
  price(
    "limone",
    "Limone",
    "pz",
    1.59,
    4,
    "Frutta e verdura",
    [],
    nutrition(29, 1, 9, 0),
  ),
  price(
    "arancia",
    "Arancia",
    "pz",
    2.19,
    6,
    "Frutta e verdura",
    [],
    nutrition(47, 1, 12, 0),
  ),
  price(
    "mele",
    "Mele",
    "g",
    2.29,
    1000,
    "Frutta e verdura",
    [],
    nutrition(52, 0, 14, 0),
  ),
  price(
    "pere",
    "Pere",
    "g",
    2.49,
    1000,
    "Frutta e verdura",
    [],
    nutrition(57, 0, 15, 0),
  ),
  price(
    "banane",
    "Banane",
    "g",
    1.89,
    1000,
    "Frutta e verdura",
    [],
    nutrition(89, 1, 23, 0),
  ),
  price(
    "fragole",
    "Fragole",
    "g",
    3.49,
    500,
    "Frutta e verdura",
    [],
    nutrition(32, 1, 8, 0),
  ),
  price(
    "cocco",
    "Cocco rapè",
    "g",
    1.99,
    250,
    "Dispensa",
    [],
    nutrition(660, 7, 24, 65),
  ),
  price(
    "mandorle",
    "Mandorle",
    "g",
    3.49,
    250,
    "Dispensa",
    ["frutta a guscio"],
    nutrition(579, 21, 22, 50),
  ),
  price(
    "nocciole",
    "Nocciole",
    "g",
    3.69,
    250,
    "Dispensa",
    ["frutta a guscio"],
    nutrition(628, 15, 17, 61),
  ),
  price(
    "marmellata",
    "Marmellata",
    "g",
    2.19,
    350,
    "Dispensa",
    [],
    nutrition(250, 0, 62, 0),
  ),
  price(
    "mascarpone",
    "Mascarpone",
    "g",
    2.79,
    250,
    "Latticini",
    ["latte"],
    nutrition(429, 5, 4, 44),
  ),
  price(
    "caffe",
    "Caffè",
    "g",
    3.49,
    250,
    "Dispensa",
    [],
    nutrition(2, 0, 0, 0),
  ),
  price(
    "biscotti-secchi",
    "Biscotti secchi",
    "g",
    1.79,
    400,
    "Dispensa",
    ["glutine", "latte"],
    nutrition(430, 7, 72, 13),
  ),
  price(
    "panna",
    "Panna fresca",
    "ml",
    2.19,
    250,
    "Latticini",
    ["latte"],
    nutrition(337, 2, 3, 35),
  ),
  price(
    "amido-mais",
    "Amido di mais",
    "g",
    1.49,
    250,
    "Dispensa",
    [],
    nutrition(381, 0, 91, 0),
  ),
  price(
    "farina-riso",
    "Farina di riso",
    "g",
    1.99,
    500,
    "Dispensa",
    [],
    nutrition(366, 6, 80, 1),
  ),
];

const ingredientById = new Map(dessertPrices.map((item) => [item.id, item]));
const sharedIngredients: Record<string, Omit<Ingredient, "quantity">> = {
  farina: {
    id: "farina",
    name: "Farina di grano",
    unit: "g",
    category: "Dispensa",
    allergens: ["glutine"],
  },
  uova: {
    id: "uova",
    name: "Uova",
    unit: "pz",
    category: "Carne e pesce",
    allergens: ["uova"],
  },
  yogurt: {
    id: "yogurt",
    name: "Yogurt greco",
    unit: "g",
    category: "Latticini",
    allergens: ["latte"],
  },
  ricotta: {
    id: "ricotta",
    name: "Ricotta",
    unit: "g",
    category: "Latticini",
    allergens: ["latte"],
  },
  avena: {
    id: "avena",
    name: "Fiocchi d'avena",
    unit: "g",
    category: "Dispensa",
    allergens: ["glutine"],
  },
  carote: {
    id: "carote",
    name: "Carote",
    unit: "g",
    category: "Frutta e verdura",
    allergens: [],
  },
};

const makeIngredient = ([id, quantity]: [string, number]): Ingredient => {
  const catalog = ingredientById.get(id);
  const shared = sharedIngredients[id];
  if (!catalog && !shared)
    throw new Error(`Ingrediente dolce sconosciuto: ${id}`);
  return catalog
    ? {
        id,
        name: catalog.name,
        unit: catalog.unit,
        quantity,
        category: catalog.category,
        allergens: catalog.allergens,
      }
    : { ...shared, quantity };
};

interface DessertSpec {
  id: string;
  title: string;
  kind: string;
  minutes: number;
  ingredients: Array<[string, number]>;
  lowFodmap?: boolean;
}

const specs: DessertSpec[] = [
  {
    id: "torta-margherita",
    title: "Torta margherita",
    kind: "torta",
    minutes: 50,
    ingredients: [
      ["farina", 240],
      ["zucchero", 160],
      ["uova", 3],
      ["burro", 100],
      ["lievito-dolci", 16],
    ],
  },
  {
    id: "torta-cioccolato",
    title: "Torta al cioccolato",
    kind: "torta",
    minutes: 55,
    ingredients: [
      ["farina", 220],
      ["zucchero", 160],
      ["uova", 3],
      ["cacao", 50],
      ["burro", 100],
    ],
  },
  {
    id: "torta-mele",
    title: "Torta di mele",
    kind: "torta",
    minutes: 60,
    ingredients: [
      ["farina", 220],
      ["mele", 400],
      ["zucchero", 130],
      ["uova", 2],
      ["burro", 80],
    ],
  },
  {
    id: "torta-pere-cioccolato",
    title: "Torta pere e cioccolato",
    kind: "torta",
    minutes: 60,
    ingredients: [
      ["farina", 220],
      ["pere", 350],
      ["cioccolato-fondente", 120],
      ["uova", 2],
      ["zucchero", 120],
    ],
  },
  {
    id: "torta-arancia",
    title: "Torta soffice all'arancia",
    kind: "torta",
    minutes: 50,
    ingredients: [
      ["farina", 240],
      ["arancia", 2],
      ["zucchero", 140],
      ["uova", 3],
      ["burro", 80],
    ],
  },
  {
    id: "torta-limone",
    title: "Torta al limone",
    kind: "torta",
    minutes: 50,
    ingredients: [
      ["farina", 240],
      ["limone", 2],
      ["zucchero", 150],
      ["uova", 3],
      ["yogurt", 125],
    ],
  },
  {
    id: "torta-yogurt",
    title: "Torta allo yogurt",
    kind: "torta",
    minutes: 45,
    ingredients: [
      ["farina", 240],
      ["yogurt", 250],
      ["zucchero", 130],
      ["uova", 2],
      ["lievito-dolci", 16],
    ],
  },
  {
    id: "torta-ricotta",
    title: "Torta di ricotta",
    kind: "torta",
    minutes: 55,
    ingredients: [
      ["farina", 180],
      ["ricotta", 350],
      ["zucchero", 140],
      ["uova", 3],
      ["limone", 1],
    ],
  },
  {
    id: "torta-nocciole",
    title: "Torta alle nocciole",
    kind: "torta",
    minutes: 50,
    ingredients: [
      ["farina", 180],
      ["nocciole", 180],
      ["zucchero", 140],
      ["uova", 3],
      ["burro", 80],
    ],
  },
  {
    id: "torta-mandorle",
    title: "Torta alle mandorle",
    kind: "torta",
    minutes: 50,
    ingredients: [
      ["farina", 160],
      ["mandorle", 200],
      ["zucchero", 130],
      ["uova", 3],
      ["limone", 1],
    ],
  },
  {
    id: "crostata-marmellata",
    title: "Crostata alla marmellata",
    kind: "crostata",
    minutes: 55,
    ingredients: [
      ["farina", 300],
      ["burro", 150],
      ["zucchero", 110],
      ["uova", 2],
      ["marmellata", 300],
    ],
  },
  {
    id: "crostata-cioccolato",
    title: "Crostata al cioccolato",
    kind: "crostata",
    minutes: 60,
    ingredients: [
      ["farina", 300],
      ["burro", 150],
      ["zucchero", 100],
      ["uova", 2],
      ["cioccolato-fondente", 220],
    ],
  },
  {
    id: "crostata-limone",
    title: "Crostata al limone",
    kind: "crostata",
    minutes: 65,
    ingredients: [
      ["farina", 300],
      ["burro", 140],
      ["zucchero", 150],
      ["uova", 3],
      ["limone", 3],
    ],
  },
  {
    id: "crostata-ricotta",
    title: "Crostata ricotta e cacao",
    kind: "crostata",
    minutes: 65,
    ingredients: [
      ["farina", 300],
      ["burro", 140],
      ["ricotta", 350],
      ["cacao", 30],
      ["zucchero", 140],
    ],
  },
  {
    id: "crostata-mele",
    title: "Crostata di mele",
    kind: "crostata",
    minutes: 65,
    ingredients: [
      ["farina", 300],
      ["burro", 140],
      ["mele", 450],
      ["zucchero", 120],
      ["limone", 1],
    ],
  },
  {
    id: "biscotti-frolla",
    title: "Biscotti di pasta frolla",
    kind: "biscotti",
    minutes: 35,
    ingredients: [
      ["farina", 300],
      ["burro", 150],
      ["zucchero", 100],
      ["uova", 1],
    ],
  },
  {
    id: "biscotti-cioccolato",
    title: "Biscotti al cioccolato",
    kind: "biscotti",
    minutes: 35,
    ingredients: [
      ["farina", 260],
      ["burro", 120],
      ["zucchero", 110],
      ["uova", 1],
      ["cioccolato-fondente", 120],
    ],
  },
  {
    id: "biscotti-avena",
    title: "Biscotti avena e miele",
    kind: "biscotti",
    minutes: 30,
    ingredients: [
      ["avena", 220],
      ["farina", 100],
      ["miele", 90],
      ["burro", 80],
      ["uova", 1],
    ],
  },
  {
    id: "biscotti-cocco",
    title: "Biscotti al cocco",
    kind: "biscotti",
    minutes: 25,
    ingredients: [
      ["cocco", 220],
      ["zucchero", 100],
      ["uova", 2],
      ["farina", 60],
    ],
  },
  {
    id: "biscotti-limone",
    title: "Biscotti al limone",
    kind: "biscotti",
    minutes: 30,
    ingredients: [
      ["farina", 280],
      ["burro", 110],
      ["zucchero", 100],
      ["uova", 1],
      ["limone", 2],
    ],
  },
  {
    id: "biscotti-arancia",
    title: "Biscotti all'arancia",
    kind: "biscotti",
    minutes: 30,
    ingredients: [
      ["farina", 280],
      ["burro", 110],
      ["zucchero", 100],
      ["uova", 1],
      ["arancia", 2],
    ],
  },
  {
    id: "biscotti-nocciole",
    title: "Biscotti alle nocciole",
    kind: "biscotti",
    minutes: 35,
    ingredients: [
      ["farina", 220],
      ["nocciole", 130],
      ["burro", 100],
      ["zucchero", 100],
      ["uova", 1],
    ],
  },
  {
    id: "biscotti-mandorle",
    title: "Biscotti alle mandorle",
    kind: "biscotti",
    minutes: 35,
    ingredients: [
      ["farina", 220],
      ["mandorle", 130],
      ["burro", 100],
      ["zucchero", 100],
      ["uova", 1],
    ],
  },
  {
    id: "cookies",
    title: "Cookies con gocce di cioccolato",
    kind: "biscotti",
    minutes: 30,
    ingredients: [
      ["farina", 260],
      ["burro", 130],
      ["zucchero", 140],
      ["uova", 1],
      ["cioccolato-fondente", 150],
    ],
  },
  {
    id: "brownies",
    title: "Brownies fondenti",
    kind: "tortini",
    minutes: 40,
    ingredients: [
      ["cioccolato-fondente", 220],
      ["burro", 150],
      ["zucchero", 150],
      ["uova", 3],
      ["farina", 100],
    ],
  },
  {
    id: "muffin-cioccolato",
    title: "Muffin al cioccolato",
    kind: "tortini",
    minutes: 35,
    ingredients: [
      ["farina", 240],
      ["cacao", 40],
      ["zucchero", 120],
      ["uova", 2],
      ["latte", 180],
    ],
  },
  {
    id: "muffin-mirtilli-fragole",
    title: "Muffin alle fragole",
    kind: "tortini",
    minutes: 35,
    ingredients: [
      ["farina", 250],
      ["fragole", 180],
      ["zucchero", 120],
      ["uova", 2],
      ["yogurt", 125],
    ],
  },
  {
    id: "muffin-banane",
    title: "Muffin alla banana",
    kind: "tortini",
    minutes: 35,
    ingredients: [
      ["farina", 240],
      ["banane", 280],
      ["zucchero", 90],
      ["uova", 2],
      ["burro", 80],
    ],
  },
  {
    id: "cupcake-vaniglia",
    title: "Cupcake alla vaniglia",
    kind: "tortini",
    minutes: 40,
    ingredients: [
      ["farina", 220],
      ["zucchero", 130],
      ["uova", 2],
      ["burro", 110],
      ["vaniglia", 2],
    ],
  },
  {
    id: "tortino-cuore-caldo",
    title: "Tortino dal cuore caldo",
    kind: "tortini",
    minutes: 25,
    ingredients: [
      ["cioccolato-fondente", 180],
      ["burro", 120],
      ["uova", 3],
      ["zucchero", 80],
      ["farina", 50],
    ],
  },
  {
    id: "plumcake-yogurt",
    title: "Plumcake allo yogurt",
    kind: "merendina",
    minutes: 50,
    ingredients: [
      ["farina", 260],
      ["yogurt", 200],
      ["zucchero", 130],
      ["uova", 3],
      ["lievito-dolci", 16],
    ],
  },
  {
    id: "plumcake-cacao",
    title: "Plumcake al cacao",
    kind: "merendina",
    minutes: 50,
    ingredients: [
      ["farina", 230],
      ["cacao", 40],
      ["latte", 160],
      ["zucchero", 140],
      ["uova", 3],
    ],
  },
  {
    id: "ciambellone",
    title: "Ciambellone della nonna",
    kind: "torta",
    minutes: 55,
    ingredients: [
      ["farina", 300],
      ["zucchero", 160],
      ["uova", 3],
      ["latte", 180],
      ["lievito-dolci", 16],
    ],
  },
  {
    id: "banana-bread",
    title: "Banana bread",
    kind: "merendina",
    minutes: 60,
    ingredients: [
      ["farina", 240],
      ["banane", 350],
      ["uova", 2],
      ["zucchero", 90],
      ["burro", 80],
    ],
  },
  {
    id: "camille",
    title: "Camille fatte in casa",
    kind: "merendina",
    minutes: 40,
    ingredients: [
      ["farina", 200],
      ["carote", 250],
      ["mandorle", 80],
      ["zucchero", 120],
      ["uova", 2],
    ],
  },
  {
    id: "fette-latte",
    title: "Fette al latte fatte in casa",
    kind: "merendina",
    minutes: 50,
    ingredients: [
      ["farina", 150],
      ["cacao", 30],
      ["uova", 3],
      ["panna", 200],
      ["miele", 40],
    ],
  },
  {
    id: "bounty",
    title: "Bounty fatti in casa",
    kind: "merendina",
    minutes: 30,
    ingredients: [
      ["cocco", 220],
      ["latte", 100],
      ["zucchero", 70],
      ["cioccolato-fondente", 220],
    ],
  },
  {
    id: "mars",
    title: "Barrette tipo Mars",
    kind: "merendina",
    minutes: 35,
    ingredients: [
      ["cioccolato-latte", 240],
      ["burro", 80],
      ["miele", 100],
      ["biscotti-secchi", 180],
    ],
  },
  {
    id: "snickers",
    title: "Barrette tipo Snickers",
    kind: "merendina",
    minutes: 40,
    ingredients: [
      ["cioccolato-latte", 240],
      ["nocciole", 160],
      ["miele", 100],
      ["burro", 70],
    ],
  },
  {
    id: "twix",
    title: "Barrette tipo Twix",
    kind: "merendina",
    minutes: 45,
    ingredients: [
      ["farina", 220],
      ["burro", 150],
      ["zucchero", 100],
      ["miele", 100],
      ["cioccolato-latte", 200],
    ],
  },
  {
    id: "kinder-cereali",
    title: "Barrette tipo Kinder Cereali",
    kind: "merendina",
    minutes: 30,
    ingredients: [
      ["cioccolato-latte", 240],
      ["cioccolato-fondente", 80],
      ["avena", 140],
      ["miele", 60],
    ],
  },
  {
    id: "salame-cioccolato",
    title: "Salame di cioccolato",
    kind: "dolce freddo",
    minutes: 25,
    ingredients: [
      ["biscotti-secchi", 280],
      ["cacao", 50],
      ["burro", 120],
      ["zucchero", 100],
      ["uova", 1],
    ],
  },
  {
    id: "tiramisù",
    title: "Tiramisù classico",
    kind: "dolce al cucchiaio",
    minutes: 35,
    ingredients: [
      ["biscotti-secchi", 300],
      ["mascarpone", 500],
      ["uova", 4],
      ["zucchero", 100],
      ["caffe", 50],
    ],
  },
  {
    id: "tiramisù-fragole",
    title: "Tiramisù alle fragole",
    kind: "dolce al cucchiaio",
    minutes: 35,
    ingredients: [
      ["biscotti-secchi", 300],
      ["mascarpone", 500],
      ["fragole", 350],
      ["zucchero", 100],
    ],
  },
  {
    id: "cheesecake-fragole",
    title: "Cheesecake alle fragole",
    kind: "dolce freddo",
    minutes: 45,
    ingredients: [
      ["biscotti-secchi", 260],
      ["burro", 110],
      ["ricotta", 300],
      ["panna", 200],
      ["fragole", 300],
    ],
  },
  {
    id: "cheesecake-cioccolato",
    title: "Cheesecake al cioccolato",
    kind: "dolce freddo",
    minutes: 45,
    ingredients: [
      ["biscotti-secchi", 260],
      ["burro", 110],
      ["ricotta", 300],
      ["panna", 200],
      ["cioccolato-fondente", 180],
    ],
  },
  {
    id: "panna-cotta",
    title: "Panna cotta alla vaniglia",
    kind: "dolce al cucchiaio",
    minutes: 25,
    ingredients: [
      ["panna", 500],
      ["zucchero", 90],
      ["vaniglia", 2],
      ["amido-mais", 20],
    ],
  },
  {
    id: "budino-cioccolato",
    title: "Budino al cioccolato",
    kind: "dolce al cucchiaio",
    minutes: 25,
    ingredients: [
      ["latte", 500],
      ["cacao", 45],
      ["zucchero", 80],
      ["amido-mais", 45],
    ],
  },
  {
    id: "budino-vaniglia",
    title: "Budino alla vaniglia",
    kind: "dolce al cucchiaio",
    minutes: 25,
    ingredients: [
      ["latte", 500],
      ["zucchero", 80],
      ["vaniglia", 2],
      ["amido-mais", 45],
    ],
  },
  {
    id: "crema-catalana",
    title: "Crema catalana",
    kind: "dolce al cucchiaio",
    minutes: 35,
    ingredients: [
      ["latte", 500],
      ["uova", 4],
      ["zucchero", 110],
      ["amido-mais", 30],
      ["limone", 1],
    ],
  },
  {
    id: "creme-caramel",
    title: "Crème caramel",
    kind: "dolce al cucchiaio",
    minutes: 60,
    ingredients: [
      ["latte", 500],
      ["uova", 4],
      ["zucchero", 150],
      ["vaniglia", 2],
    ],
  },
  {
    id: "semifreddo-caffe",
    title: "Semifreddo al caffè",
    kind: "dolce freddo",
    minutes: 30,
    ingredients: [
      ["panna", 400],
      ["mascarpone", 250],
      ["caffe", 50],
      ["zucchero", 100],
    ],
  },
  {
    id: "semifreddo-nocciola",
    title: "Semifreddo alla nocciola",
    kind: "dolce freddo",
    minutes: 35,
    ingredients: [
      ["panna", 400],
      ["nocciole", 160],
      ["zucchero", 100],
      ["cioccolato-fondente", 80],
    ],
  },
  {
    id: "gelato-banana",
    title: "Gelato veloce alla banana",
    kind: "dolce freddo",
    minutes: 10,
    ingredients: [
      ["banane", 500],
      ["yogurt", 200],
      ["miele", 40],
    ],
  },
  {
    id: "sorbetto-limone",
    title: "Sorbetto al limone",
    kind: "dolce freddo",
    minutes: 20,
    ingredients: [
      ["limone", 5],
      ["zucchero", 180],
    ],
  },
  {
    id: "sorbetto-fragola",
    title: "Sorbetto alla fragola",
    kind: "dolce freddo",
    minutes: 20,
    ingredients: [
      ["fragole", 500],
      ["zucchero", 140],
      ["limone", 1],
    ],
    lowFodmap: true,
  },
  {
    id: "tortino-riso-cacao",
    title: "Tortino di riso al cacao",
    kind: "tortini",
    minutes: 30,
    ingredients: [
      ["farina-riso", 180],
      ["cacao", 35],
      ["uova", 2],
      ["zucchero", 100],
    ],
    lowFodmap: true,
  },
  {
    id: "biscotti-riso-limone",
    title: "Biscotti di riso al limone",
    kind: "biscotti",
    minutes: 30,
    ingredients: [
      ["farina-riso", 250],
      ["burro", 100],
      ["zucchero", 90],
      ["uova", 1],
      ["limone", 1],
    ],
    lowFodmap: true,
  },
  {
    id: "tartufi-cocco",
    title: "Tartufi al cocco",
    kind: "dolcetti",
    minutes: 20,
    ingredients: [
      ["cocco", 200],
      ["ricotta", 220],
      ["zucchero", 70],
      ["cacao", 25],
    ],
  },
  {
    id: "tartufi-cioccolato",
    title: "Tartufi al cioccolato",
    kind: "dolcetti",
    minutes: 25,
    ingredients: [
      ["cioccolato-fondente", 220],
      ["panna", 120],
      ["cacao", 30],
      ["nocciole", 60],
    ],
  },
];

export const dessertRecipes: Recipe[] = specs.map((spec) => {
  const ingredients = spec.ingredients.map(makeIngredient);
  const allergenSet = new Set(
    ingredients.flatMap((item) => item.allergens ?? []),
  );
  const tags: Recipe["tags"] = ["dolci", "vegetariani"];
  if (!allergenSet.has("glutine")) tags.push("senza glutine");
  if (!allergenSet.has("latte")) tags.push("senza lattosio");
  if (spec.lowFodmap) tags.push("low FODMAP");
  return {
    id: `dolce-${spec.id}`,
    title: spec.title,
    time: spec.minutes,
    difficulty: spec.minutes > 55 ? "Media" : "Facile",
    ingredients,
    steps: buildDessertSteps({
      title: spec.title,
      kind: spec.kind,
      ingredients,
    }),
    nutrition: nutrition(320, 6, 42, 14),
    tags,
    allergens: [...allergenSet],
    baseServings: 8,
    course: "Dolce",
    origin: "seed",
  };
});
