import { buildSavorySteps } from "./procedures";
import { PriceItem, Recipe, RecipeCourse } from "./types";

const nutrition = (
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
) => ({
  calories,
  protein,
  carbs,
  fat,
});

const storesFor = (base: number) => ({
  Lidl: +(base * 0.92).toFixed(2),
  Eurospin: +(base * 0.88).toFixed(2),
  Esselunga: +(base * 1.08).toFixed(2),
  Coop: +(base * 1.1).toFixed(2),
  Conad: +(base * 1.04).toFixed(2),
  Despar: +(base * 1.06).toFixed(2),
  Penny: +(base * 0.9).toFixed(2),
  MD: +(base * 0.89).toFixed(2),
  Altro: base,
});

const price = (
  id: string,
  name: string,
  unit: "g" | "ml" | "pz",
  base: number,
  per: number,
  category: PriceItem["category"],
  allergens: string[],
  values = nutrition(0, 0, 0, 0),
): PriceItem => ({
  id,
  name,
  unit,
  price: base,
  per,
  packageQuantity: per,
  category,
  allergens,
  nutrition: values,
  stores: storesFor(base),
});

export const savoryPrices: PriceItem[] = [
  price(
    "salsa-soia",
    "Salsa di soia",
    "ml",
    2.39,
    150,
    "Dispensa",
    ["soia", "glutine"],
    nutrition(53, 8, 5, 0),
  ),
  price(
    "zenzero",
    "Zenzero fresco",
    "g",
    1.49,
    200,
    "Frutta e verdura",
    [],
    nutrition(80, 2, 18, 1),
  ),
  price(
    "aglio",
    "Aglio",
    "g",
    1.49,
    150,
    "Frutta e verdura",
    [],
    nutrition(149, 6, 33, 1),
  ),
  price(
    "cavolo",
    "Cavolo cappuccio",
    "g",
    1.59,
    800,
    "Frutta e verdura",
    [],
    nutrition(25, 1, 6, 0),
  ),
  price(
    "latte-cocco",
    "Latte di cocco",
    "ml",
    1.89,
    400,
    "Dispensa",
    [],
    nutrition(180, 2, 3, 18),
  ),
  price(
    "curry",
    "Curry in polvere",
    "g",
    1.59,
    50,
    "Dispensa",
    [],
    nutrition(325, 14, 56, 14),
  ),
  price(
    "gamberi",
    "Gamberi sgusciati",
    "g",
    5.49,
    300,
    "Carne e pesce",
    ["crostacei"],
    nutrition(99, 24, 0, 0),
  ),
  price(
    "sesamo",
    "Semi di sesamo",
    "g",
    1.79,
    150,
    "Dispensa",
    ["sesamo"],
    nutrition(573, 18, 23, 50),
  ),
  price(
    "noodles-riso",
    "Noodles di riso",
    "g",
    2.39,
    250,
    "Dispensa",
    [],
    nutrition(360, 6, 80, 1),
  ),
  price(
    "noodles-grano",
    "Noodles di grano",
    "g",
    2.19,
    250,
    "Dispensa",
    ["glutine"],
    nutrition(350, 11, 70, 3),
  ),
  price(
    "lime",
    "Lime",
    "pz",
    1.99,
    4,
    "Frutta e verdura",
    [],
    nutrition(30, 1, 11, 0),
  ),
  price(
    "arachidi",
    "Arachidi tostate",
    "g",
    1.89,
    200,
    "Dispensa",
    ["arachidi"],
    nutrition(585, 24, 21, 49),
  ),
  price(
    "miso",
    "Miso",
    "g",
    3.49,
    300,
    "Dispensa",
    ["soia"],
    nutrition(199, 12, 26, 6),
  ),
  price(
    "alga-nori",
    "Alga nori",
    "g",
    2.49,
    25,
    "Dispensa",
    [],
    nutrition(306, 30, 44, 5),
  ),
  price(
    "cavolfiore",
    "Cavolfiore",
    "g",
    2.19,
    800,
    "Frutta e verdura",
    [],
    nutrition(25, 2, 5, 0),
  ),
  price(
    "mais",
    "Mais in scatola",
    "g",
    1.09,
    285,
    "Dispensa",
    [],
    nutrition(86, 3, 19, 1),
  ),
  price(
    "couscous",
    "Cous cous",
    "g",
    1.59,
    500,
    "Dispensa",
    ["glutine"],
    nutrition(376, 13, 77, 1),
  ),
];

type Method = "wok" | "curry" | "soup" | "oven" | "pan" | "rice";

interface SavorySpec {
  id: string;
  title: string;
  minutes: number;
  course: RecipeCourse;
  method: Method;
  ingredients: Array<[string, number]>;
  asian?: boolean;
  tags?: Recipe["tags"];
}

const asian: SavorySpec[] = [
  {
    id: "pollo-teriyaki",
    title: "Pollo teriyaki con riso",
    minutes: 35,
    course: "Secondo",
    method: "wok",
    asian: true,
    ingredients: [
      ["pollo", 320],
      ["riso", 180],
      ["salsa-soia", 45],
      ["miele", 25],
      ["zenzero", 12],
    ],
  },
  {
    id: "riso-cantonese",
    title: "Riso alla cantonese",
    minutes: 30,
    course: "Primo",
    method: "rice",
    asian: true,
    ingredients: [
      ["riso", 220],
      ["uova", 2],
      ["piselli", 160],
      ["maiale", 140],
      ["salsa-soia", 30],
    ],
  },
  {
    id: "noodles-tofu",
    title: "Noodles con tofu e verdure",
    minutes: 25,
    course: "Primo",
    method: "wok",
    asian: true,
    ingredients: [
      ["noodles-grano", 220],
      ["tofu", 240],
      ["zucchine", 180],
      ["carote", 140],
      ["salsa-soia", 35],
    ],
  },
  {
    id: "curry-ceci-cocco",
    title: "Curry di ceci al cocco",
    minutes: 35,
    course: "Primo",
    method: "curry",
    asian: true,
    ingredients: [
      ["ceci", 300],
      ["latte-cocco", 300],
      ["curry", 12],
      ["pomodori", 220],
      ["riso", 180],
    ],
  },
  {
    id: "salmone-miso",
    title: "Salmone al miso con riso",
    minutes: 35,
    course: "Secondo",
    method: "oven",
    asian: true,
    ingredients: [
      ["salmone", 320],
      ["miso", 45],
      ["riso", 180],
      ["broccoli", 260],
      ["sesamo", 15],
    ],
  },
  {
    id: "pad-thai-gamberi",
    title: "Pad thai con gamberi",
    minutes: 30,
    course: "Primo",
    method: "wok",
    asian: true,
    ingredients: [
      ["noodles-riso", 220],
      ["gamberi", 260],
      ["uova", 2],
      ["arachidi", 35],
      ["lime", 2],
    ],
  },
  {
    id: "udon-manzo",
    title: "Udon saltati con manzo",
    minutes: 30,
    course: "Primo",
    method: "wok",
    asian: true,
    ingredients: [
      ["noodles-grano", 240],
      ["manzo", 260],
      ["cavolo", 200],
      ["salsa-soia", 35],
      ["zenzero", 10],
    ],
  },
  {
    id: "riso-fritto-tofu",
    title: "Riso fritto con tofu",
    minutes: 25,
    course: "Primo",
    method: "rice",
    asian: true,
    ingredients: [
      ["riso", 220],
      ["tofu", 240],
      ["uova", 2],
      ["piselli", 150],
      ["salsa-soia", 30],
    ],
  },
  {
    id: "pollo-curry-thai",
    title: "Pollo al curry thai",
    minutes: 40,
    course: "Secondo",
    method: "curry",
    asian: true,
    ingredients: [
      ["pollo", 340],
      ["latte-cocco", 300],
      ["curry", 12],
      ["peperoni", 220],
      ["riso", 180],
    ],
  },
  {
    id: "gyoza-maiale",
    title: "Gyoza di maiale e cavolo",
    minutes: 55,
    course: "Secondo",
    method: "pan",
    asian: true,
    ingredients: [
      ["farina", 220],
      ["maiale", 260],
      ["cavolo", 200],
      ["zenzero", 10],
      ["salsa-soia", 30],
    ],
  },
  {
    id: "onigiri-salmone",
    title: "Onigiri al salmone",
    minutes: 40,
    course: "Primo",
    method: "rice",
    asian: true,
    ingredients: [
      ["riso", 260],
      ["salmone", 180],
      ["alga-nori", 10],
      ["sesamo", 15],
    ],
  },
  {
    id: "bibimbap",
    title: "Bibimbap con manzo e verdure",
    minutes: 45,
    course: "Primo",
    method: "rice",
    asian: true,
    ingredients: [
      ["riso", 220],
      ["manzo", 240],
      ["spinaci", 180],
      ["carote", 140],
      ["uova", 2],
      ["salsa-soia", 30],
    ],
  },
  {
    id: "japchae",
    title: "Japchae con manzo e sesamo",
    minutes: 35,
    course: "Primo",
    method: "wok",
    asian: true,
    ingredients: [
      ["noodles-riso", 230],
      ["manzo", 220],
      ["spinaci", 160],
      ["carote", 130],
      ["sesamo", 18],
    ],
  },
  {
    id: "yakisoba-pollo",
    title: "Yakisoba con pollo",
    minutes: 30,
    course: "Primo",
    method: "wok",
    asian: true,
    ingredients: [
      ["noodles-grano", 240],
      ["pollo", 260],
      ["cavolo", 180],
      ["carote", 120],
      ["salsa-soia", 35],
    ],
  },
  {
    id: "dal-curry",
    title: "Dal speziato con riso",
    minutes: 40,
    course: "Primo",
    method: "curry",
    asian: true,
    ingredients: [
      ["lenticchie", 240],
      ["curry", 10],
      ["pomodori", 240],
      ["riso", 180],
      ["zenzero", 10],
    ],
  },
  {
    id: "chana-masala",
    title: "Chana masala",
    minutes: 40,
    course: "Primo",
    method: "curry",
    asian: true,
    ingredients: [
      ["ceci", 320],
      ["curry", 12],
      ["pomodori", 250],
      ["cipolle", 120],
      ["riso", 180],
    ],
  },
  {
    id: "aloo-gobi",
    title: "Aloo gobi",
    minutes: 40,
    course: "Contorno",
    method: "curry",
    asian: true,
    ingredients: [
      ["patate", 360],
      ["cavolfiore", 360],
      ["curry", 10],
      ["pomodori", 180],
      ["zenzero", 10],
    ],
  },
  {
    id: "mapo-tofu",
    title: "Mapo tofu delicato",
    minutes: 30,
    course: "Secondo",
    method: "wok",
    asian: true,
    ingredients: [
      ["tofu", 300],
      ["manzo", 180],
      ["salsa-soia", 35],
      ["zenzero", 10],
      ["riso", 180],
    ],
  },
  {
    id: "zuppa-miso",
    title: "Zuppa di miso e tofu",
    minutes: 20,
    course: "Primo",
    method: "soup",
    asian: true,
    ingredients: [
      ["miso", 55],
      ["tofu", 220],
      ["alga-nori", 8],
      ["zenzero", 8],
      ["carote", 120],
    ],
  },
  {
    id: "nasi-goreng",
    title: "Nasi goreng con pollo",
    minutes: 30,
    course: "Primo",
    method: "rice",
    asian: true,
    ingredients: [
      ["riso", 220],
      ["pollo", 240],
      ["uova", 2],
      ["salsa-soia", 35],
      ["carote", 130],
    ],
  },
];

const international: SavorySpec[] = [
  {
    id: "couscous-ceci-verdure",
    title: "Cous cous con ceci e verdure",
    minutes: 25,
    course: "Primo",
    method: "pan",
    ingredients: [
      ["couscous", 220],
      ["ceci", 260],
      ["zucchine", 180],
      ["peperoni", 180],
      ["limone", 1],
    ],
    tags: ["economici", "salutari"],
  },
  {
    id: "pasta-ricotta-limone",
    title: "Pasta ricotta e limone",
    minutes: 22,
    course: "Primo",
    method: "pan",
    ingredients: [
      ["pasta", 220],
      ["ricotta", 220],
      ["limone", 1],
      ["parmigiano", 40],
    ],
    tags: ["veloci", "classici italiani"],
  },
  {
    id: "lasagna-padella",
    title: "Lasagna veloce in padella",
    minutes: 40,
    course: "Primo",
    method: "pan",
    ingredients: [
      ["pasta", 240],
      ["pomodori", 320],
      ["ricotta", 220],
      ["mozzarella", 180],
      ["parmigiano", 40],
    ],
    tags: ["classici italiani"],
  },
  {
    id: "polpette-tacchino",
    title: "Polpette di tacchino al pomodoro",
    minutes: 40,
    course: "Secondo",
    method: "pan",
    ingredients: [
      ["tacchino", 380],
      ["uova", 1],
      ["farina", 45],
      ["pomodori", 300],
    ],
    tags: ["high protein", "classici italiani"],
  },
  {
    id: "burger-lenticchie",
    title: "Burger di lenticchie e carote",
    minutes: 35,
    course: "Secondo",
    method: "pan",
    ingredients: [
      ["lenticchie", 280],
      ["carote", 160],
      ["farina", 60],
      ["uova", 1],
    ],
    tags: ["economici", "salutari"],
  },
  {
    id: "quinoa-mediterranea",
    title: "Quinoa mediterranea",
    minutes: 25,
    course: "Primo",
    method: "rice",
    ingredients: [
      ["quinoa", 220],
      ["pomodori", 180],
      ["zucchine", 180],
      ["olive", 60],
      ["ceci", 180],
    ],
    tags: ["salutari", "veloci"],
  },
  {
    id: "peperoni-ripieni",
    title: "Peperoni ripieni di riso e manzo",
    minutes: 55,
    course: "Secondo",
    method: "oven",
    ingredients: [
      ["peperoni", 500],
      ["riso", 180],
      ["manzo", 260],
      ["pomodori", 180],
      ["mozzarella", 100],
    ],
  },
  {
    id: "parmigiana-melanzane",
    title: "Parmigiana leggera di melanzane",
    minutes: 60,
    course: "Secondo",
    method: "oven",
    ingredients: [
      ["melanzane", 600],
      ["pomodori", 350],
      ["mozzarella", 220],
      ["parmigiano", 50],
    ],
    tags: ["classici italiani", "vegetariani"],
  },
  {
    id: "torta-salata-spinaci",
    title: "Torta salata ricotta e spinaci",
    minutes: 55,
    course: "Secondo",
    method: "oven",
    ingredients: [
      ["farina", 260],
      ["ricotta", 280],
      ["spinaci", 300],
      ["uova", 2],
      ["parmigiano", 40],
    ],
    tags: ["vegetariani"],
  },
  {
    id: "pasta-zucca-ricotta",
    title: "Pasta cremosa zucca e ricotta",
    minutes: 35,
    course: "Primo",
    method: "pan",
    ingredients: [
      ["pasta", 220],
      ["zucca", 360],
      ["ricotta", 180],
      ["parmigiano", 35],
    ],
    tags: ["classici italiani", "vegetariani"],
  },
  {
    id: "risotto-funghi",
    title: "Risotto ai funghi",
    minutes: 35,
    course: "Primo",
    method: "rice",
    ingredients: [
      ["riso", 220],
      ["funghi", 320],
      ["parmigiano", 45],
      ["cipolle", 80],
    ],
    tags: ["classici italiani", "vegetariani"],
  },
  {
    id: "polenta-funghi",
    title: "Polenta con funghi e parmigiano",
    minutes: 35,
    course: "Primo",
    method: "pan",
    ingredients: [
      ["polenta", 220],
      ["funghi", 320],
      ["parmigiano", 45],
      ["cipolle", 80],
    ],
    tags: ["economici", "vegetariani"],
  },
  {
    id: "merluzzo-olive",
    title: "Merluzzo al pomodoro e olive",
    minutes: 30,
    course: "Secondo",
    method: "pan",
    ingredients: [
      ["merluzzo", 380],
      ["pomodori", 280],
      ["olive", 70],
      ["patate", 300],
    ],
    tags: ["salutari", "senza glutine"],
  },
  {
    id: "salmone-mandorle",
    title: "Salmone in crosta di mandorle",
    minutes: 35,
    course: "Secondo",
    method: "oven",
    ingredients: [
      ["salmone", 360],
      ["mandorle", 80],
      ["limone", 1],
      ["zucchine", 300],
    ],
    tags: ["high protein", "salutari"],
  },
  {
    id: "pollo-limone-patate",
    title: "Pollo al limone con patate",
    minutes: 45,
    course: "Secondo",
    method: "oven",
    ingredients: [
      ["pollo", 380],
      ["limone", 2],
      ["patate", 420],
      ["carote", 180],
    ],
    tags: ["high protein", "senza glutine"],
  },
  {
    id: "maiale-mele",
    title: "Lonza di maiale alle mele",
    minutes: 45,
    course: "Secondo",
    method: "pan",
    ingredients: [
      ["maiale", 380],
      ["mele", 260],
      ["cipolle", 100],
      ["patate", 320],
    ],
  },
  {
    id: "spezzatino-manzo",
    title: "Spezzatino di manzo con patate",
    minutes: 75,
    course: "Secondo",
    method: "soup",
    ingredients: [
      ["manzo", 420],
      ["patate", 420],
      ["carote", 180],
      ["pomodori", 220],
      ["cipolle", 100],
    ],
    tags: ["classici italiani"],
  },
  {
    id: "frittata-broccoli-ricotta",
    title: "Frittata broccoli e ricotta",
    minutes: 35,
    course: "Secondo",
    method: "pan",
    ingredients: [
      ["uova", 5],
      ["broccoli", 300],
      ["ricotta", 180],
      ["parmigiano", 35],
    ],
    tags: ["high protein", "vegetariani"],
  },
  {
    id: "hummus-bowl",
    title: "Hummus bowl con verdure",
    minutes: 25,
    course: "Secondo",
    method: "pan",
    ingredients: [
      ["ceci", 320],
      ["sesamo", 35],
      ["carote", 180],
      ["zucchine", 180],
      ["pane", 160],
    ],
    tags: ["salutari", "economici"],
  },
  {
    id: "burrito-riso-fagioli",
    title: "Burrito bowl con riso e fagioli",
    minutes: 30,
    course: "Primo",
    method: "rice",
    ingredients: [
      ["riso", 220],
      ["fagioli", 260],
      ["mais", 160],
      ["peperoni", 180],
      ["mozzarella", 100],
    ],
    tags: ["economici"],
  },
  {
    id: "chili-manzo",
    title: "Chili di manzo e fagioli",
    minutes: 45,
    course: "Secondo",
    method: "soup",
    ingredients: [
      ["manzo", 300],
      ["fagioli", 280],
      ["mais", 160],
      ["pomodori", 300],
      ["cipolle", 100],
    ],
    tags: ["high protein"],
  },
  {
    id: "quesadilla-pollo",
    title: "Quesadilla di pollo e peperoni",
    minutes: 35,
    course: "Secondo",
    method: "pan",
    ingredients: [
      ["farina", 220],
      ["pollo", 280],
      ["peperoni", 200],
      ["mozzarella", 180],
      ["pomodori", 120],
    ],
  },
  {
    id: "couscous-salmone",
    title: "Cous cous con salmone e zucchine",
    minutes: 30,
    course: "Primo",
    method: "pan",
    ingredients: [
      ["couscous", 220],
      ["salmone", 280],
      ["zucchine", 240],
      ["limone", 1],
    ],
    tags: ["salutari"],
  },
  {
    id: "quinoa-tofu-peperoni",
    title: "Quinoa con tofu e peperoni",
    minutes: 30,
    course: "Primo",
    method: "rice",
    ingredients: [
      ["quinoa", 220],
      ["tofu", 260],
      ["peperoni", 220],
      ["zucchine", 180],
    ],
    tags: ["salutari"],
  },
  {
    id: "uova-forno-spinaci",
    title: "Uova al forno con spinaci e ricotta",
    minutes: 30,
    course: "Secondo",
    method: "oven",
    ingredients: [
      ["uova", 4],
      ["spinaci", 300],
      ["ricotta", 180],
      ["parmigiano", 35],
    ],
    tags: ["high protein", "vegetariani"],
  },
  {
    id: "vellutata-piselli",
    title: "Vellutata di piselli e patate",
    minutes: 35,
    course: "Primo",
    method: "soup",
    ingredients: [
      ["piselli", 360],
      ["patate", 300],
      ["cipolle", 80],
      ["yogurt", 100],
    ],
    tags: ["economici", "vegetariani"],
  },
  {
    id: "insalata-patate-tonno",
    title: "Insalata di patate, tonno e olive",
    minutes: 30,
    course: "Contorno",
    method: "pan",
    ingredients: [
      ["patate", 420],
      ["tonno", 220],
      ["olive", 70],
      ["pomodori", 180],
    ],
    tags: ["veloci", "senza glutine"],
  },
  {
    id: "pasta-tonno-olive",
    title: "Pasta con tonno, pomodoro e olive",
    minutes: 25,
    course: "Primo",
    method: "pan",
    ingredients: [
      ["pasta", 220],
      ["tonno", 220],
      ["pomodori", 260],
      ["olive", 60],
    ],
    tags: ["veloci", "classici italiani"],
  },
  {
    id: "cavolfiore-ceci-forno",
    title: "Cavolfiore e ceci croccanti",
    minutes: 40,
    course: "Contorno",
    method: "oven",
    ingredients: [
      ["cavolfiore", 500],
      ["ceci", 260],
      ["curry", 8],
      ["yogurt", 120],
    ],
    tags: ["salutari", "economici"],
  },
  {
    id: "melanzane-ripiene-quinoa",
    title: "Melanzane ripiene di quinoa",
    minutes: 55,
    course: "Secondo",
    method: "oven",
    ingredients: [
      ["melanzane", 560],
      ["quinoa", 200],
      ["pomodori", 220],
      ["mozzarella", 140],
    ],
    tags: ["vegetariani", "salutari"],
  },
];

export const savoryRecipeSpecs = [...asian, ...international];

const animalIds = new Set([
  "pollo",
  "salmone",
  "tonno",
  "tacchino",
  "manzo",
  "maiale",
  "merluzzo",
  "gamberi",
  "uova",
  "mozzarella",
  "ricotta",
  "parmigiano",
  "yogurt",
]);
const meatIds = new Set([
  "pollo",
  "salmone",
  "tonno",
  "tacchino",
  "manzo",
  "maiale",
  "merluzzo",
  "gamberi",
]);

const baseSteps = (method: Method): string[] => {
  if (method === "wok")
    return [
      "Cuoci separatamente la parte amidacea prevista e scolala un minuto prima del tempo indicato sulla confezione.",
      "Rosola prima la proteina e poi le verdure, mantenendo la padella molto calda per non farle bollire.",
      "Unisci salsa, parte amidacea e ingredienti cotti; salta brevemente finché il condimento riveste tutto in modo uniforme.",
    ];
  if (method === "curry")
    return [
      "Scalda le spezie per 30 secondi a calore medio, senza farle annerire.",
      "Aggiungi gli ingredienti più tenaci, quindi la componente liquida, e porta a leggero fremito.",
      "Cuoci coperto per 18–22 minuti e mescola ogni 5 minuti; il fondo deve risultare cremoso e non acquoso.",
    ];
  if (method === "soup")
    return [
      "Taglia gli ingredienti in pezzi di circa 2 cm, così raggiungono la cottura nello stesso momento.",
      "Porta lentamente a leggero bollore e cuoci con coperchio socchiuso per 25–35 minuti.",
      "Controlla la morbidezza, poi frulla solo la parte prevista o lascia la preparazione rustica come indicato dal titolo.",
    ];
  if (method === "oven")
    return [
      "Disponi gli ingredienti in un solo strato o in strati regolari, evitando zone troppo spesse.",
      "Inforna nel forno statico già caldo e ruota la teglia a metà cottura per uniformare la doratura.",
      "Controlla il centro della preparazione prima di sfornare e lascia assestare 5 minuti.",
    ];
  if (method === "rice")
    return [
      "Sciacqua il cereale finché l'acqua è quasi limpida, poi cuocilo mantenendo i chicchi separati.",
      "Prepara in padella gli altri componenti rispettando l'ordine: proteine, ortaggi più duri, ortaggi teneri.",
      "Unisci il cereale cotto e mescola a calore vivace per 2–3 minuti, distribuendo bene tutti gli ingredienti.",
    ];
  return [
    "Cuoci prima gli ingredienti che richiedono più tempo e tieni pronti gli altri in ciotole separate.",
    "Rosola o amalgama i componenti nell'ordine indicato dal titolo, senza sovraccaricare la padella.",
    "Unisci tutti gli elementi e completa la cottura finché il fondo è legato e le consistenze sono uniformi.",
  ];
};

export const createSavoryRecipes = (catalog: PriceItem[]): Recipe[] =>
  savoryRecipeSpecs.map((spec) => {
    const ingredients = spec.ingredients.map(([id, quantity]) => {
      const item = catalog.find((candidate) => candidate.id === id);
      if (!item)
        throw new Error(`Ingrediente ricetta salata sconosciuto: ${id}`);
      return {
        id: item.id,
        name: item.name,
        unit: item.unit,
        quantity,
        category: item.category,
        allergens: [...item.allergens],
      };
    });
    const ids = new Set(ingredients.map((ingredient) => ingredient.id));
    const allergens = [
      ...new Set(
        ingredients.flatMap((ingredient) => ingredient.allergens ?? []),
      ),
    ];
    const tags = new Set<Recipe["tags"][number]>(spec.tags ?? []);
    if (spec.asian) tags.add("asiatici");
    if (![...ids].some((id) => meatIds.has(id))) tags.add("vegetariani");
    if (![...ids].some((id) => animalIds.has(id))) tags.add("vegani");
    if (!allergens.includes("glutine")) tags.add("senza glutine");
    if (!allergens.includes("latte")) tags.add("senza lattosio");
    const draft = {
      title: spec.title,
      ingredients,
      steps: baseSteps(spec.method),
      time: spec.minutes,
    };
    return {
      id: `salato-${spec.id}`,
      title: spec.title,
      time: spec.minutes,
      difficulty: spec.minutes >= 50 ? "Media" : "Facile",
      ingredients,
      steps: buildSavorySteps(draft),
      nutrition: nutrition(510, 25, 58, 18),
      tags: [...tags],
      allergens,
      baseServings: 2,
      course: spec.course,
      origin: "seed",
    };
  });
