import { PriceItem, Recipe } from "./types";

const n = (calories: number, protein: number, carbs: number, fat: number) => ({ calories, protein, carbs, fat });
export const seedPrices: PriceItem[] = [
 {id:"pasta",name:"Pasta integrale",unit:"g",price:1.35,per:500,category:"Dispensa",allergens:["glutine"],nutrition:n(350,13,68,2),stores:{Esselunga:1.55,Lidl:1.19,Eurospin:1.09,Coop:1.59,Conad:1.49}},
 {id:"riso",name:"Riso basmati",unit:"g",price:2.2,per:500,category:"Dispensa",allergens:[],nutrition:n(350,7,78,1),stores:{Esselunga:2.35,Lidl:1.89,Eurospin:1.75,Coop:2.39,Conad:2.2}},
 {id:"ceci",name:"Ceci in barattolo",unit:"g",price:0.85,per:240,category:"Dispensa",allergens:[],nutrition:n(120,6,18,2),stores:{Esselunga:0.95,Lidl:0.75,Eurospin:0.69,Coop:0.99,Conad:0.89}},
 {id:"lenticchie",name:"Lenticchie rosse",unit:"g",price:1.75,per:400,category:"Dispensa",allergens:[],nutrition:n(330,25,50,1),stores:{Esselunga:1.99,Lidl:1.55,Eurospin:1.39,Coop:2.05,Conad:1.85}},
 {id:"pollo",name:"Petto di pollo",unit:"g",price:4.9,per:500,category:"Carne e pesce",allergens:[],nutrition:n(110,23,0,2),stores:{Esselunga:5.7,Lidl:4.5,Eurospin:4.2,Coop:5.9,Conad:5.2}},
 {id:"salmone",name:"Salmone",unit:"g",price:6.9,per:400,category:"Carne e pesce",allergens:["pesce"],nutrition:n(200,20,0,13),stores:{Esselunga:7.5,Lidl:6.4,Eurospin:6.1,Coop:7.8,Conad:7.1}},
 {id:"uova",name:"Uova",unit:"pz",price:2.45,per:6,category:"Carne e pesce",allergens:["uova"],nutrition:n(140,13,1,10),stores:{Esselunga:2.7,Lidl:2.1,Eurospin:1.95,Coop:2.8,Conad:2.55}},
 {id:"tofu",name:"Tofu naturale",unit:"g",price:2.29,per:200,category:"Frutta e verdura",allergens:["soia"],nutrition:n(120,14,2,7),stores:{Esselunga:2.49,Lidl:1.99,Coop:2.69,Conad:2.39}},
 {id:"pomodori",name:"Passata di pomodoro",unit:"g",price:0.89,per:700,category:"Dispensa",allergens:[],nutrition:n(30,1,5,0),stores:{Esselunga:1.09,Lidl:0.75,Eurospin:0.65,Coop:1.15,Conad:0.95}},
 {id:"zucchine",name:"Zucchine",unit:"g",price:1.99,per:500,category:"Frutta e verdura",allergens:[],nutrition:n(17,1,3,0),stores:{Esselunga:2.19,Lidl:1.69,Eurospin:1.49,Coop:2.29,Conad:2.05}},
 {id:"spinaci",name:"Spinaci surgelati",unit:"g",price:1.49,per:450,category:"Surgelati",allergens:[],nutrition:n(25,3,2,0),stores:{Esselunga:1.75,Lidl:1.25,Eurospin:1.19,Coop:1.79,Conad:1.55}},
 {id:"pane",name:"Pane senza glutine",unit:"g",price:3.1,per:300,category:"Dispensa",allergens:[],nutrition:n(240,4,45,4),stores:{Esselunga:3.29,Coop:3.35,Conad:3.2}},
 {id:"yogurt",name:"Yogurt greco",unit:"g",price:1.79,per:500,category:"Latticini",allergens:["latte"],nutrition:n(70,9,4,2),stores:{Esselunga:1.99,Lidl:1.49,Eurospin:1.39,Coop:2.1,Conad:1.85}},
 {id:"avena",name:"Fiocchi d'avena",unit:"g",price:1.39,per:500,category:"Dispensa",allergens:["glutine"],nutrition:n(370,13,60,7),stores:{Esselunga:1.59,Lidl:1.15,Eurospin:0.99,Coop:1.69,Conad:1.45,Vivo:1.29,"Contè":1.19,Despar:1.55,Penny:1.09}},
 {id:"tonno",name:"Tonno al naturale",unit:"g",price:2.35,per:160,category:"Carne e pesce",allergens:["pesce"],nutrition:n(110,25,0,1),stores:{Esselunga:2.59,Lidl:1.99,Eurospin:1.89,Coop:2.69,Conad:2.45,Vivo:2.19,"Contè":2.09,Despar:2.5,Penny:1.95}},
 {id:"fagioli",name:"Fagioli cannellini",unit:"g",price:0.79,per:240,category:"Dispensa",allergens:[],nutrition:n(90,6,14,1),stores:{Esselunga:0.95,Lidl:0.69,Eurospin:0.65,Coop:0.99,Conad:0.89,Vivo:0.75,"Contè":0.72,Despar:0.9,Penny:0.69}},
 {id:"broccoli",name:"Broccoli",unit:"g",price:1.89,per:500,category:"Frutta e verdura",allergens:[],nutrition:n(34,3,4,0),stores:{Esselunga:2.09,Lidl:1.55,Eurospin:1.49,Coop:2.15,Conad:1.99,Vivo:1.75,"Contè":1.69,Despar:2,Penny:1.59}},
 {id:"patate",name:"Patate",unit:"g",price:1.49,per:1000,category:"Frutta e verdura",allergens:[],nutrition:n(77,2,17,0),stores:{Esselunga:1.69,Lidl:1.19,Eurospin:0.99,Coop:1.75,Conad:1.55,Vivo:1.29,"Contè":1.19,Despar:1.6,Penny:1.09}},
 {id:"tacchino",name:"Fesa di tacchino",unit:"g",price:5.35,per:500,category:"Carne e pesce",allergens:[],nutrition:n(105,24,0,1),stores:{Esselunga:5.9,Lidl:4.95,Eurospin:4.69,Coop:6.1,Conad:5.65,Vivo:5.1,"Contè":4.99,Despar:5.6,Penny:4.85}},
 {id:"mozzarella",name:"Mozzarella",unit:"g",price:1.25,per:125,category:"Latticini",allergens:["latte"],nutrition:n(250,18,2,19),stores:{Esselunga:1.45,Lidl:0.99,Eurospin:0.89,Coop:1.55,Conad:1.35,Vivo:1.15,"Contè":1.09,Despar:1.4,Penny:0.99}}
];
const ing = (id:string, quantity:number, unit:"g"|"ml"|"pz"="g") => { const p=seedPrices.find(x=>x.id===id)!; return {id,name:p.name,quantity,unit,category:p.category,allergens:p.allergens}; };
const baseRecipes: Recipe[] = [
 {id:"pasta-ceci",title:"Pasta cremosa ai ceci",time:22,difficulty:"Facile",ingredients:[ing("pasta",180),ing("ceci",240),ing("pomodori",250)],steps:["Cuoci la pasta in acqua salata.","Scalda ceci e passata con poca acqua.","Frulla una parte dei ceci e manteca la pasta."],nutrition:n(520,20,88,8),tags:["economici","classici italiani","vegetariani"],allergens:["glutine"],baseServings:2},
 {id:"pollo-riso",title:"Pollo, riso e zucchine",time:28,difficulty:"Facile",ingredients:[ing("pollo",300),ing("riso",180),ing("zucchine",300)],steps:["Lessare il riso.","Rosolare il pollo a bocconcini.","Saltare le zucchine e unire tutto."],nutrition:n(510,40,61,10),tags:["high protein","salutari","senza lattosio"],allergens:[],baseServings:2},
 {id:"dahl",title:"Dahl veloce di lenticchie",time:25,difficulty:"Facile",ingredients:[ing("lenticchie",180),ing("riso",160),ing("spinaci",200)],steps:["Sciacquare le lenticchie.","Cuocerle con acqua per 15 minuti.","Unire spinaci e servire con riso."],nutrition:n(490,25,80,5),tags:["veloci","economici","vegani","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"tofu-zucchine",title:"Tofu dorato con zucchine",time:20,difficulty:"Facile",ingredients:[ing("tofu",300),ing("riso",170),ing("zucchine",350)],steps:["Cuoci il riso.","Rosola il tofu a cubetti.","Aggiungi zucchine sottili e servi."],nutrition:n(460,25,65,13),tags:["veloci","vegani","salutari","senza glutine","senza lattosio"],allergens:["soia"],baseServings:2},
 {id:"salmone-spinaci",title:"Salmone con spinaci e riso",time:25,difficulty:"Media",ingredients:[ing("salmone",280),ing("riso",170),ing("spinaci",250)],steps:["Cuoci il riso.","Cuoci il salmone in padella 4 minuti per lato.","Salta gli spinaci e componi il piatto."],nutrition:n(590,38,62,22),tags:["high protein","salutari","senza glutine","senza lattosio"],allergens:["pesce"],baseServings:2},
 {id:"uova-pomodoro",title:"Uova al pomodoro con pane",time:18,difficulty:"Facile",ingredients:[ing("uova",4,"pz"),ing("pomodori",300),ing("pane",160)],steps:["Scalda la passata.","Apri le uova nel sugo e copri.","Servi quando l'albume è cotto con pane tostato."],nutrition:n(430,23,42,17),tags:["veloci","economici","vegetariani","senza glutine"],allergens:["uova"],baseServings:2},
 {id:"pasta-zucchine",title:"Pasta alle zucchine e pomodoro",time:24,difficulty:"Facile",ingredients:[ing("pasta",180),ing("zucchine",350),ing("pomodori",250)],steps:["Cuoci la pasta.","Salta le zucchine con la passata.","Unisci e completa con erbe."],nutrition:n(470,15,85,7),tags:["veloci","economici","classici italiani","vegetariani"],allergens:["glutine"],baseServings:2},
 {id:"insalata-tonno",title:"Insalata di riso e tonno",time:18,difficulty:"Facile",ingredients:[ing("riso",180),ing("tonno",160),ing("zucchine",250)],steps:["Cuoci e raffredda il riso.","Griglia le zucchine.","Mescola con tonno e limone."],nutrition:n(480,29,64,8),tags:["veloci","salutari","senza glutine","senza lattosio"],allergens:["pesce"],baseServings:2},
 {id:"tacchino-broccoli",title:"Tacchino con broccoli e patate",time:32,difficulty:"Facile",ingredients:[ing("tacchino",300),ing("broccoli",350),ing("patate",400)],steps:["Cuoci le patate al forno.","Salta i broccoli.","Rosola il tacchino e servi."],nutrition:n(500,42,52,10),tags:["high protein","salutari","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"fagioli-riso",title:"Riso, fagioli e spinaci",time:20,difficulty:"Facile",ingredients:[ing("riso",180),ing("fagioli",240),ing("spinaci",250)],steps:["Cuoci il riso.","Scalda i fagioli con gli spinaci.","Unisci e condisci con olio."],nutrition:n(460,18,82,6),tags:["economici","vegani","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"pasta-mozzarella",title:"Pasta filante al pomodoro",time:20,difficulty:"Facile",ingredients:[ing("pasta",180),ing("pomodori",300),ing("mozzarella",200)],steps:["Cuoci la pasta.","Scalda il pomodoro.","Unisci mozzarella a cubetti fuori dal fuoco."],nutrition:n(560,27,80,16),tags:["veloci","classici italiani","vegetariani"],allergens:["glutine","latte"],baseServings:2},
 {id:"ceci-patate",title:"Ceci speziati con patate",time:30,difficulty:"Facile",ingredients:[ing("ceci",240),ing("patate",500),ing("spinaci",200)],steps:["Arrostisci le patate.","Scalda i ceci con spezie dolci.","Aggiungi spinaci e servi."],nutrition:n(450,16,72,7),tags:["economici","vegani","senza glutine","senza lattosio"],allergens:[],baseServings:2}
];
const moreRecipes: Recipe[] = [
 {id:"pasta-fagioli",title:"Pasta e fagioli vellutata",time:35,difficulty:"Facile",ingredients:[ing("pasta",160),ing("fagioli",300),ing("pomodori",220)],steps:["Sciacqua i fagioli e scaldali per 8 minuti con la passata e un mestolo d'acqua.","Frulla un terzo del composto, poi rimettilo nella casseruola per ottenere una base cremosa.","Cuoci la pasta al dente, conservando poca acqua di cottura.","Unisci pasta e crema, regola la densità e lascia riposare 2 minuti prima di servire."],nutrition:n(510,21,91,7),tags:["economici","classici italiani","vegetariani"],allergens:["glutine"],baseServings:2},
 {id:"riso-salmone-zucchine",title:"Riso con salmone e zucchine",time:30,difficulty:"Facile",ingredients:[ing("riso",180),ing("salmone",260),ing("zucchine",300)],steps:["Sciacqua il riso e cuocilo mantenendo i chicchi consistenti.","Taglia le zucchine sottili e falle dorare in padella per 7 minuti.","Cuoci il salmone a cubetti nella stessa padella finché risulta opaco al centro.","Aggiungi il riso, mescola delicatamente e completa con scorza di limone."],nutrition:n(570,36,67,18),tags:["salutari","high protein","senza glutine","senza lattosio"],allergens:["pesce"],baseServings:2},
 {id:"frittata-spinaci",title:"Frittata soffice agli spinaci",time:22,difficulty:"Facile",ingredients:[ing("uova",5,"pz"),ing("spinaci",300),ing("patate",250)],steps:["Cuoci le patate a cubetti in acqua leggermente salata per 8 minuti.","Strizza gli spinaci e ripassali in padella finché perdono l'umidità.","Sbatti le uova, incorpora verdure e patate e versa in una padella calda.","Cuoci coperto a fuoco basso, gira la frittata e termina la doratura."],nutrition:n(420,27,32,21),tags:["economici","vegetariani","senza glutine"],allergens:["uova"],baseServings:2},
 {id:"pollo-pomodoro",title:"Pollo morbido al pomodoro",time:28,difficulty:"Facile",ingredients:[ing("pollo",320),ing("pomodori",350),ing("patate",350)],steps:["Taglia il pollo in pezzi uniformi e asciugalo bene.","Rosolalo a fiamma vivace finché forma una crosticina su tutti i lati.","Aggiungi la passata, abbassa il fuoco e cuoci coperto per 12 minuti.","Servi con le patate lessate e lascia restringere il fondo se necessario."],nutrition:n(470,43,39,13),tags:["high protein","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"tofu-broccoli",title:"Tofu croccante e broccoli",time:25,difficulty:"Facile",ingredients:[ing("tofu",300),ing("broccoli",400),ing("riso",160)],steps:["Tampona il tofu, taglialo a cubetti e fallo dorare senza muoverlo troppo.","Dividi i broccoli in cimette e cuocili al vapore per 5 minuti.","Salta tofu e broccoli insieme con spezie e poca acqua.","Distribuisci sul riso caldo e completa con succo di limone."],nutrition:n(480,27,61,15),tags:["vegani","salutari","senza glutine","senza lattosio"],allergens:["soia"],baseServings:2},
 {id:"zuppa-lenticchie-patate",title:"Zuppa di lenticchie e patate",time:38,difficulty:"Facile",ingredients:[ing("lenticchie",190),ing("patate",400),ing("pomodori",220)],steps:["Sciacqua le lenticchie finché l'acqua diventa limpida.","Taglia le patate a piccoli cubi così cuoceranno in modo uniforme.","Riunisci tutto in casseruola con passata e acqua, poi fai sobbollire per 25 minuti.","Schiaccia qualche patata, regola sale e consistenza e riposa 5 minuti."],nutrition:n(440,22,76,5),tags:["economici","vegani","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"pasta-tonno-pomodoro",title:"Pasta al tonno e pomodoro",time:20,difficulty:"Facile",ingredients:[ing("pasta",180),ing("tonno",160),ing("pomodori",300)],steps:["Porta a bollore l'acqua e cuoci la pasta un minuto meno del tempo indicato.","Scalda dolcemente la passata finché perde il sapore crudo.","Sgocciola il tonno e aggiungilo al sugo senza sfaldarlo troppo.","Salta la pasta nel condimento con poca acqua di cottura e servi subito."],nutrition:n(540,31,78,10),tags:["veloci","classici italiani","senza lattosio"],allergens:["glutine","pesce"],baseServings:2},
 {id:"insalata-ceci-patate",title:"Insalata tiepida di ceci e patate",time:25,difficulty:"Facile",ingredients:[ing("ceci",300),ing("patate",450),ing("spinaci",180)],steps:["Lessa le patate con la buccia, poi pelale e tagliale quando sono tiepide.","Sciacqua accuratamente i ceci e asciugali.","Fai appassire brevemente gli spinaci in padella.","Mescola gli ingredienti con olio, limone e pepe senza rompere le patate."],nutrition:n(430,16,69,9),tags:["economici","vegani","salutari","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"riso-uova-spinaci",title:"Riso saltato con uova e spinaci",time:18,difficulty:"Facile",ingredients:[ing("riso",180),ing("uova",3,"pz"),ing("spinaci",250)],steps:["Cuoci il riso e allargalo su un piatto per far uscire il vapore.","Strapazza le uova in padella lasciandole ancora morbide, poi mettile da parte.","Salta gli spinaci e aggiungi il riso ormai asciutto.","Rimetti le uova, mescola per un minuto e servi ben caldo."],nutrition:n(500,22,69,15),tags:["veloci","economici","vegetariani","senza glutine"],allergens:["uova"],baseServings:2},
 {id:"tacchino-zucchine",title:"Bocconcini di tacchino e zucchine",time:22,difficulty:"Facile",ingredients:[ing("tacchino",320),ing("zucchine",400),ing("riso",160)],steps:["Taglia tacchino e zucchine in pezzi della stessa dimensione.","Rosola il tacchino in una padella ampia e trasferiscilo su un piatto.","Cuoci le zucchine a fiamma vivace mantenendole consistenti.","Riunisci tutto, aggiungi poca acqua, fai glassare e servi con il riso."],nutrition:n(490,44,57,9),tags:["veloci","high protein","salutari","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"pasta-broccoli",title:"Pasta cremosa ai broccoli",time:27,difficulty:"Facile",ingredients:[ing("pasta",180),ing("broccoli",420),ing("ceci",120)],steps:["Dividi i broccoli e cuocili nella stessa acqua che userai per la pasta.","Preleva metà broccoli e frullali con ceci e poca acqua di cottura.","Cuoci la pasta al dente e conserva un mestolo d'acqua.","Manteca con la crema, aggiungi le cimette rimaste e regola la consistenza."],nutrition:n(500,21,86,7),tags:["economici","vegani","classici italiani","senza lattosio"],allergens:["glutine"],baseServings:2},
 {id:"salmone-patate",title:"Salmone al forno con patate",time:40,difficulty:"Facile",ingredients:[ing("salmone",300),ing("patate",500),ing("zucchine",250)],steps:["Taglia le patate sottili, condiscile e cuocile in forno caldo per 18 minuti.","Aggiungi le zucchine e mescola per distribuire il calore.","Adagia il salmone sulle verdure e condiscilo con limone ed erbe.","Prosegui per 12-15 minuti, finché il pesce si sfalda facilmente."],nutrition:n(620,38,52,28),tags:["salutari","high protein","senza glutine","senza lattosio"],allergens:["pesce"],baseServings:2},
 {id:"burger-fagioli",title:"Burger di fagioli e patate",time:35,difficulty:"Media",ingredients:[ing("fagioli",300),ing("patate",300),ing("spinaci",160)],steps:["Lessa le patate e schiacciale ancora calde.","Asciuga bene i fagioli, schiacciali grossolanamente e uniscili alle patate.","Forma burger compatti con mani umide e falli riposare 10 minuti.","Rosolali su entrambi i lati e servi con gli spinaci saltati."],nutrition:n(410,18,68,7),tags:["economici","vegani","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"pollo-broccoli",title:"Pollo e broccoli in padella",time:24,difficulty:"Facile",ingredients:[ing("pollo",320),ing("broccoli",400),ing("riso",160)],steps:["Sbollenta le cimette per 4 minuti e scolale molto bene.","Taglia il pollo a strisce sottili e rosolalo a fiamma alta.","Aggiungi i broccoli, spezie e due cucchiai d'acqua.","Lascia insaporire finché il fondo è lucido e servi con il riso."],nutrition:n(500,45,58,9),tags:["veloci","high protein","salutari","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"riso-lenticchie",title:"Riso speziato con lenticchie",time:28,difficulty:"Facile",ingredients:[ing("riso",170),ing("lenticchie",170),ing("pomodori",200)],steps:["Sciacqua separatamente riso e lenticchie.","Fai sobbollire le lenticchie nella passata allungata con acqua.","Cuoci il riso e sgranalo con una forchetta.","Unisci i due elementi, aggiungi spezie tostate e riposa coperto 3 minuti."],nutrition:n(490,23,89,4),tags:["economici","vegani","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"uova-zucchine",title:"Uova strapazzate con zucchine",time:15,difficulty:"Facile",ingredients:[ing("uova",5,"pz"),ing("zucchine",350),ing("pane",140)],steps:["Grattugia le zucchine e strizzale per eliminare l'acqua.","Saltale in padella per 5 minuti a fiamma vivace.","Abbassa il fuoco, versa le uova sbattute e mescola lentamente.","Spegni quando sono ancora cremose e servi con pane tostato."],nutrition:n(430,27,39,20),tags:["veloci","economici","vegetariani","senza glutine"],allergens:["uova"],baseServings:2},
 {id:"tofu-pomodoro",title:"Tofu al pomodoro con riso",time:22,difficulty:"Facile",ingredients:[ing("tofu",300),ing("pomodori",320),ing("riso",170)],steps:["Tampona il tofu e doralo a cubetti su tutti i lati.","Versa la passata nella padella e insaporisci con erbe secche.","Cuoci dolcemente per 10 minuti, girando il tofu una volta.","Servi sul riso e completa con pepe appena macinato."],nutrition:n(470,25,65,13),tags:["veloci","vegani","senza glutine","senza lattosio"],allergens:["soia"],baseServings:2},
 {id:"pasta-lenticchie",title:"Pasta e lenticchie al pomodoro",time:32,difficulty:"Facile",ingredients:[ing("pasta",160),ing("lenticchie",170),ing("pomodori",260)],steps:["Sciacqua le lenticchie e cuocile nella passata diluita per circa 18 minuti.","Aggiungi acqua calda poco alla volta per mantenere il fondo morbido.","Cuoci la pasta separatamente fino a metà cottura.","Termina la pasta nelle lenticchie mescolando spesso, poi riposa 2 minuti."],nutrition:n(520,25,93,5),tags:["economici","vegani","classici italiani","senza lattosio"],allergens:["glutine"],baseServings:2},
 {id:"tacchino-pomodoro",title:"Tacchino alla pizzaiola",time:25,difficulty:"Facile",ingredients:[ing("tacchino",320),ing("pomodori",330),ing("mozzarella",120)],steps:["Batti leggermente le fettine per uniformarne lo spessore.","Scottale in padella calda per un minuto per lato e mettile da parte.","Restringi la passata con origano, poi rimetti il tacchino.","Distribuisci la mozzarella, copri e spegni quando è appena filante."],nutrition:n(490,55,10,24),tags:["high protein","classici italiani","senza glutine"],allergens:["latte"],baseServings:2},
 {id:"patate-uova-pomodoro",title:"Padellata di patate, uova e pomodoro",time:30,difficulty:"Facile",ingredients:[ing("patate",500),ing("uova",4,"pz"),ing("pomodori",250)],steps:["Taglia le patate a cubetti piccoli e sciacquale per togliere l'amido.","Cuocile coperte con poca acqua, poi falle dorare senza coperchio.","Aggiungi la passata e crea quattro piccoli incavi.","Apri le uova negli incavi, copri e cuoci finché l'albume è fermo."],nutrition:n(460,23,52,18),tags:["economici","vegetariani","senza glutine"],allergens:["uova"],baseServings:2},
 {id:"insalata-tonno-fagioli",title:"Insalata di tonno e cannellini",time:12,difficulty:"Facile",ingredients:[ing("tonno",160),ing("fagioli",300),ing("spinaci",180)],steps:["Sciacqua i fagioli e lasciali scolare finché sono asciutti.","Sgocciola il tonno mantenendo i pezzi abbastanza grandi.","Lava e asciuga gli spinaci, poi riunisci tutto in una ciotola.","Condisci all'ultimo con limone, olio e pepe e mescola delicatamente."],nutrition:n(380,40,29,10),tags:["veloci","high protein","salutari","senza glutine","senza lattosio"],allergens:["pesce"],baseServings:2},
 {id:"risotto-zucchine",title:"Risotto semplice alle zucchine",time:30,difficulty:"Media",ingredients:[ing("riso",180),ing("zucchine",350),ing("mozzarella",100)],steps:["Grattugia metà zucchine e taglia le restanti a piccoli cubi.","Tosta il riso a secco finché è caldo al tatto.","Portalo a cottura aggiungendo acqua calda gradualmente e mescolando.","Unisci le zucchine, spegni il fuoco e manteca con la mozzarella."],nutrition:n(510,20,75,14),tags:["vegetariani","classici italiani","senza glutine"],allergens:["latte"],baseServings:2},
 {id:"pollo-patate-spinaci",title:"Pollo arrosto rapido con patate",time:38,difficulty:"Facile",ingredients:[ing("pollo",340),ing("patate",480),ing("spinaci",180)],steps:["Scalda il forno e taglia le patate a spicchi regolari.","Condisci pollo e patate separatamente, poi disponili senza sovrapporli.","Cuoci per 25 minuti, gira le patate e controlla il pollo al centro.","Lascia riposare la carne 4 minuti e servi con spinaci saltati."],nutrition:n(530,45,48,17),tags:["high protein","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"ceci-broccoli-riso",title:"Bowl di ceci, broccoli e riso",time:25,difficulty:"Facile",ingredients:[ing("ceci",280),ing("broccoli",350),ing("riso",160)],steps:["Cuoci il riso, scolalo e lascialo riposare coperto.","Arrostisci i ceci in padella finché diventano leggermente croccanti.","Cuoci i broccoli al vapore mantenendoli verdi e consistenti.","Componi le ciotole e condisci con una salsa di limone e spezie."],nutrition:n(500,21,86,8),tags:["vegani","salutari","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"salmone-zucchine",title:"Salmone in padella con zucchine",time:20,difficulty:"Facile",ingredients:[ing("salmone",300),ing("zucchine",400),ing("patate",350)],steps:["Asciuga il salmone e lascialo a temperatura ambiente per 10 minuti.","Cuocilo dal lato della pelle finché diventa croccante, poi giralo brevemente.","Nella stessa padella salta le zucchine a mezze lune.","Servi con patate lesse e versa sul piatto il fondo aromatico."],nutrition:n(590,38,39,27),tags:["veloci","salutari","high protein","senza glutine","senza lattosio"],allergens:["pesce"],baseServings:2},
 {id:"mozzarella-pomodoro-ceci",title:"Ceci alla caprese",time:12,difficulty:"Facile",ingredients:[ing("ceci",300),ing("mozzarella",250),ing("pomodori",220)],steps:["Sciacqua e asciuga molto bene i ceci.","Taglia la mozzarella e lasciala scolare per qualche minuto.","Riunisci ceci, mozzarella e pomodoro in una ciotola ampia.","Condisci con olio ed erbe, poi riposa 5 minuti prima di servire."],nutrition:n(520,31,40,27),tags:["veloci","vegetariani","senza glutine"],allergens:["latte"],baseServings:2},
 {id:"riso-tacchino-spinaci",title:"Riso con tacchino e spinaci",time:25,difficulty:"Facile",ingredients:[ing("riso",180),ing("tacchino",300),ing("spinaci",250)],steps:["Cuoci il riso e scolalo quando è ancora ben consistente.","Rosola il tacchino tagliato sottile in una padella molto calda.","Aggiungi gli spinaci poco alla volta finché appassiscono.","Unisci il riso, salta per due minuti e completa con limone."],nutrition:n(500,43,65,7),tags:["veloci","high protein","salutari","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"pasta-spinaci-mozzarella",title:"Pasta con spinaci e mozzarella",time:23,difficulty:"Facile",ingredients:[ing("pasta",180),ing("spinaci",280),ing("mozzarella",180)],steps:["Cuoci gli spinaci finché sono asciutti, poi tritane metà.","Lessa la pasta e conserva mezzo bicchiere della sua acqua.","Mescola pasta, spinaci tritati e acqua fino a creare una crema.","Aggiungi la mozzarella a fuoco spento e completa con gli spinaci interi."],nutrition:n(590,29,78,20),tags:["veloci","vegetariani","classici italiani"],allergens:["glutine","latte"],baseServings:2},
 {id:"lenticchie-broccoli",title:"Lenticchie con broccoli e patate",time:35,difficulty:"Facile",ingredients:[ing("lenticchie",180),ing("broccoli",350),ing("patate",350)],steps:["Sciacqua le lenticchie e avviane la cottura in acqua fredda.","Dopo 12 minuti aggiungi le patate tagliate piccole.","Unisci i broccoli negli ultimi 7 minuti per non sfaldarli.","Scola l'eventuale liquido, condisci e lascia assestare prima di servire."],nutrition:n(430,25,73,4),tags:["economici","vegani","salutari","senza glutine","senza lattosio"],allergens:[],baseServings:2},
 {id:"uova-fagioli",title:"Uova in umido con fagioli",time:22,difficulty:"Facile",ingredients:[ing("uova",4,"pz"),ing("fagioli",300),ing("pomodori",300)],steps:["Scalda fagioli e passata in una padella larga per 10 minuti.","Schiaccia pochi fagioli per addensare naturalmente il sugo.","Crea gli incavi e apri un uovo in ciascuno senza rompere il tuorlo.","Copri e cuoci dolcemente fino alla consistenza desiderata."],nutrition:n(440,31,35,20),tags:["economici","vegetariani","senza glutine"],allergens:["uova"],baseServings:2},
 {id:"tofu-patate-spinaci",title:"Tofu speziato con patate e spinaci",time:32,difficulty:"Facile",ingredients:[ing("tofu",300),ing("patate",420),ing("spinaci",220)],steps:["Taglia le patate piccole e lessale per 7 minuti, poi scolale.","Dora il tofu in padella con spezie fino a formare una crosta.","Aggiungi le patate e falle colorire senza mescolare troppo.","Incorpora gli spinaci, copri per 2 minuti e servi."],nutrition:n(450,25,50,17),tags:["vegani","senza glutine","senza lattosio"],allergens:["soia"],baseServings:2}
];
export const recipes: Recipe[] = [...baseRecipes, ...moreRecipes];
